---
extends: [airbnb, plugin:mocha/recommended]
env:
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
plugins: [mocha]
globals:
  describe: true
  it: true
  before: true
  after: true
  beforeEach: true
  afterEach: true
rules:
  max-len: [1, 200, 2, {"ignoreUrls":true}]
  curly: [2, "multi-line"]
  comma-dangle: [0, always-multiline]
  no-plusplus: 0
  eqeqeq: [2, "allow-null"]
  global-require: 0
  no-shadow: 1
  no-param-reassign: [2, { "props": false }]
  indent: [2, 4, { "SwitchCase": 1 }]
  padded-blocks: [2, { "switches": "always", "classes": "always" }]
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
  import/no-extraneous-dependencies: ["error", { devDependencies: ['app/test/**']}]
  no-await-in-loop: off
  mocha/no-mocha-arrows: [0]
  mocha/no-hooks-for-single-case: [0]
settings:
  import/resolver:
    node:
      extensions:
        # if unset, default is just '.js', but it must be re-added explicitly if set
        - .js
        - .jsx
        - .es6
        - .coffee

      paths:
        # an array of absolute paths which will also be searched
        # think NODE_PATH
        - /usr/local/share/global_modules

      # this is technically for identifying `node_modules` alternate names
      moduleDirectory:
        - node_modules # defaults to 'node_modules', but...
        - app/src
