apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fw
  labels:
    name: forest-watcher-api
  name: forest-watcher-api
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: forest-watcher-api
    spec:
      containers:
      - name: forest-watcher-api
        image: vizzuality/forest-watcher-api
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "4400"
          - name: NODE_ENV
            value: staging
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://forest-watcher-api.fw.svc.cluster.local:4400
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 4400

      restartPolicy: Always
